// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `flatten_proof`, `flatten_vk`, `init_logger`, `init_panic_hook`, `parse_biguint`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `G1Point`, `G2Point`, `RawProof`, `RawVk`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `fmt`, `fmt`

Future<Groth16Calldata> generateGroth16Calldata({
  required Groth16Input input,
}) => RustLib.instance.api.crateApiGenerateGroth16Calldata(input: input);

/// Output returned to Flutter
/// We return a single flat list of calldata, because that is what garaga returns.
class Groth16Calldata {
  final List<String> calldata;

  const Groth16Calldata({required this.calldata});

  @override
  int get hashCode => calldata.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Groth16Calldata &&
          runtimeType == other.runtimeType &&
          calldata == other.calldata;
}

/// Input coming from Flutter
class Groth16Input {
  final String vkJson;
  final String proofJson;
  final String publicInputsJson;

  const Groth16Input({
    required this.vkJson,
    required this.proofJson,
    required this.publicInputsJson,
  });

  @override
  int get hashCode =>
      vkJson.hashCode ^ proofJson.hashCode ^ publicInputsJson.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Groth16Input &&
          runtimeType == other.runtimeType &&
          vkJson == other.vkJson &&
          proofJson == other.proofJson &&
          publicInputsJson == other.publicInputsJson;
}
