targets:
  $default:
    builders:
      hive_generator:
        generate_for:
          include:
            - lib/**
      source_gen|combining_builder:
        options:
          ignore_for_file:
            - "type=lint"
